<?php

/**
 * @file
 * The OpenEuropa Dashboard Agent install file.
 */

declare(strict_types = 1);

use Drupal\Core\Site\Settings;
use Drupal\oe_dashboard_agent\ManifestFileReader;

/**
 * Implements hook_requirements().
 */
function oe_dashboard_agent_requirements($phase) {
  $requirements = [];

  // Show whether the token is found.
  if ($phase == 'runtime') {
    $value = Settings::get('oe_dashboard_agent.token', FALSE);
    $requirements['oe_dashboard_agent.token'] = [
      'title' => t('Dashboard agent token'),
      'value' => $value ? t('Value set') : t('Value not set'),
      'severity' => REQUIREMENT_INFO,
    ];

    $value = Settings::get('oe_dashboard_agent.allowed_ips', FALSE);
    $requirements['oe_dashboard_agent.allowed_ips'] = [
      'title' => t('Dashboard agent allowed IPs'),
      'value' => $value ? implode(', ', $value) : t('Value not set'),
      'severity' => REQUIREMENT_INFO,
    ];

    $manifest_reader = \Drupal::classResolver()->getInstanceFromDefinition(ManifestFileReader::class);
    $manifest = $manifest_reader->getData();
    $requirements['oe_dashboard_agent.site_version'] = [
      'title' => t('Site version'),
      'value' => $manifest['version'] ?? t('Value not set'),
      'severity' => REQUIREMENT_INFO,
    ];
  }

  return $requirements;
}
